var unsavedCall=!1;var client=AgoraRTC.createClient({mode:"rtc",codec:"vp8"});var localTracks={videoTrack:null,audioTrack:null};var localTrackState={videoTrackEnabled:!0,audioTrackEnabled:!0};var remoteUsers={};var options={appid:null,channel:null,uid:null,token:null,uname:null};var videoProfiles=[{label:"1920 HD",detail:"",value:"1080p_2"},{label:"1280 HIGH",detail:"",value:"720p_2"},{label:"640 STANDARD",detail:"",value:"480p_2"},{label:"200 BASIC",detail:"",value:{width:200,height:640,frameRate:30}}];var curVideoProfile;const loadImage=url=>{return new Promise((resolve,reject)=>{if(!url){reject(new Error("url is empty"))}
const image=new Image();image.src=url;image.style="display:none;width:10px;height:10px;";image.crossOrigin="anonymous";image.onload=()=>{resolve(image)};document.body.appendChild(image)})};let denoiser=null;let processor=null;let processorIsDisable=!0;let currentOption="blur";let tempSelected="blur";const optionState={currentBlurDegree:1,currentColor:"#00ff00",currentImageUrl:""};var vb_preview_effect=!1;var vb_effect=!1;const pipeProcessor=(track,processor)=>{track.pipe(processor).pipe(track.processorDestination)};$(()=>{initVideoProfiles();$(".profile-list").delegate("a","click",function(e){changeVideoProfile(this.getAttribute("label"))});var urlParams=new URL(location.href).searchParams;options.appid=urlParams.get("appid");options.channel=urlParams.get("channel");options.token=urlParams.get("token");options.uid=urlParams.get("uid");options.uname=$('#username').val();if(options.appid&&options.channel){$("#uid").val(options.uid);$("#appid").val(options.appid);$("#token").val(options.token);$("#channel").val(options.channel);$("#join-form").submit()}})
$("#join-form").submit(async function(e){e.preventDefault();$("#join").attr("disabled",!0);try{options.appid=$("#appid").val();options.token=$("#token").val();options.channel=$("#channel").val();options.uid=$("#uid").val();options.uname=$('#username').val();await join();if(options.token){$("#success-alert-with-token").css("display","block")}else{$("#success-alert a").attr("href",`index.html?appid=${options.appid}&channel=${options.channel}&token=${options.token}&uname=${options.uname}`);$("#success-alert").css("display","block")}}catch(error){console.error(error)}finally{$("#leave").attr("disabled",!1)}})
$("#mute-audio").click(function(e){if(localTrackState.audioTrackEnabled){muteAudio()}else{unmuteAudio()}});$("#mute-video").click(function(e){if(localTrackState.videoTrackEnabled){muteVideo()}else{unmuteVideo()}})
$("#leave").click(function(e){leave()})
$('#settings').on('click',function(){if($(this).attr('data-click-state')==1){$(this).attr('data-click-state',0);$(this).css({'border-radius':'30px 30px 30px 30px'});$('.profile-list').hide()}else{$(this).attr('data-click-state',1);$(this).css({'border-radius':'0px 0px 20px 20px'});$('.profile-list').show()}})
$("#mini_local_stream_div").mouseover(function(){$(this).find(".rmt-vdoinfo").removeClass('hide')})
$("#mini_local_stream_div").mouseleave(function(){$(this).find(".rmt-vdoinfo").addClass('hide')})
$('#end_call').click(function(){leave();unsavedCall=!0;setTimeout(function(){window.location.href='dashboard'},1000)});async function join(){client.on("user-published",handleUserPublished);client.on("user-unpublished",handleUserUnpublished);[options.uid,localTracks.audioTrack,localTracks.videoTrack]=await Promise.all([client.join(options.appid,options.channel,options.token||null,options.uid||null),AgoraRTC.createMicrophoneAudioTrack(),AgoraRTC.createCameraVideoTrack({encoderConfig:curVideoProfile.value})]);localTracks.videoTrack.play("local-player");var unid=options.uid.toString();var username_color=unid.slice(0,6);$("#usernamecolor").val(username_color);$("#local-player").attr('name',username_color);var postData='uid='+unid+'&username='+$('#username').val()+'&meeting_code='+$('#channel').val()+'&action=reg_agora_user';$.ajax({url:"action/callAction.php",type:"POST",data:postData,cache:!1,success:function(data,textStatus,jqXHR){},error:function(xhr,status,error){}});await client.publish(Object.values(localTracks))}
async function leave(){for(trackName in localTracks){var track=localTracks[trackName];if(track){track.stop();track.close();localTracks[trackName]=undefined}}
remoteUsers={};$("#remote-playerlist").html("");await client.leave();$("#join").attr("disabled",!1);$("#leave").attr("disabled",!0)}
async function subscribe(user,mediaType){const uid=user.uid;await client.subscribe(user,mediaType);var postData='uid='+uid+'&meeting_code='+$('#channel').val()+'&action=get_reg_agora_user';$.ajax({url:"action/callAction.php",type:"POST",data:postData,cache:!1,success:function(data,textStatus,jqXHR){if(mediaType==='video'){$(`#player-wrapper-${uid}`).parent('.video-tile').remove();var unid=uid.toString();var username_color=unid.slice(0,6);const username=data;const player=$(`
                <div class="video-tile" name="${username_color}" namepl="${username}">
                    <box-icon id="player-${uid}-mute" class="mute_bg" name='microphone' type='solid' color='#ffffff'></box-icon>
                    <div class="player_name">${username}</div>
                    <div id="player-wrapper-${uid}">
                    <div id="player-${uid}" class=""></div>
                    </div>
                </div>
            `);var player_count=$('#tiles-count').val()?parseInt($('#tiles-count').val()):(parseInt($('.video-tile').length)+1);$('#tiles-count').val(player_count);const gapBetweenTiles=10;const wrapper=document.getElementById("remote-playerlist");const input=document.getElementById("tiles-count");const renderNewTiles=(tilesCount)=>{Array.from({length:tilesCount},(_,i)=>i+1).forEach(()=>{$("#remote-playerlist").append(player)})};wrapper.style.gap=`${gapBetweenTiles}px`;renderNewTiles(player_count);const tiles=document.getElementsByClassName("video-tile");const elementsInARowCount=Math.ceil(Math.sqrt(tiles.length));const tilesArray=[...tiles];tilesArray.forEach((element)=>{if(tiles.length>elementsInARowCount){$('.video-tile').addClass('video-tile-2')}else{$('.video-tile').removeClass('video-tile-2')}
element.style.width=`calc(calc(70% / ${elementsInARowCount}) - ${gapBetweenTiles}px)`});user.videoTrack.play(`player-${uid}`);if(remoteUsers[uid]._audio_muted_===!0){$(`#player-${uid}-mute`).removeAttr("name");$(`#player-${uid}-mute`).attr('name','microphone-off')}else{$(`#player-${uid}-mute`).removeAttr("name");$(`#player-${uid}-mute`).attr('name','microphone')}
Clock.start()}
if(mediaType==='audio'){if(remoteUsers[uid]._audio_muted_===!0){$(`#player-${uid}-mute`).removeAttr("name");$(`#player-${uid}-mute`).attr('name','microphone-off')}else{$(`#player-${uid}-mute`).removeAttr("name");$(`#player-${uid}-mute`).attr('name','microphone')}
user.audioTrack.play()}},error:function(xhr,status,error){window.location.reload()}})}
function initVideoProfiles(){videoProfiles.forEach(profile=>{$(".profile-list").append(`<a class="dropdown-item" style="border-radius:0px;width:100%; border-bottom:1px dashed #ccc; color:#fff;margin:2px 0px 0px 0px;background:#00000085;" label="${profile.label}" href="#">${profile.label}</a>`)});curVideoProfile=videoProfiles[0]}
async function changeVideoProfile(label){curVideoProfile=videoProfiles.find(profile=>profile.label===label);localTracks.videoTrack&&await localTracks.videoTrack.setEncoderConfiguration(curVideoProfile.value)}
async function muteAudio(){if(!localTracks.audioTrack)
return;await localTracks.audioTrack.setEnabled(!1);localTrackState.audioTrackEnabled=!1;$("#mute-audio").addClass("close");$("#mute-audio").find("box-icon").removeAttr("name");$("#mute-audio").find("box-icon").attr("name","microphone-off")}
async function muteVideo(){if(!localTracks.videoTrack)
return;await localTracks.videoTrack.setEnabled(!1);localTrackState.videoTrackEnabled=!1;$("#mute-video").addClass("close");$("#mute-video").find("box-icon").removeAttr("name");$("#mute-video").find("box-icon").attr("name","camera-off");$('#local-player').html('<div class="player_name">'+$('#username').val()+'</div><div class="novideo">'+$('#username').val().charAt(0)+'</div>');$('#local-player').find('.novideo').css('background','#'+$('#usernamecolor').val())}
async function unmuteAudio(){if(!localTracks.audioTrack)
return;await localTracks.audioTrack.setEnabled(!0);localTrackState.audioTrackEnabled=!0;$("#mute-audio").removeClass("close");$("#mute-audio").find("box-icon").removeAttr("name");$("#mute-audio").find("box-icon").attr("name","microphone")}
async function unmuteVideo(){$('#local-player').find('.mini_placeholder').html('');if(!localTracks.videoTrack)
return;await localTracks.videoTrack.setEnabled(!0);localTrackState.videoTrackEnabled=!0;$("#mute-video").removeClass("close");$("#mute-video").find("box-icon").removeAttr("name");$("#mute-video").find("box-icon").attr("name","camera");$('#local-player').find('.novideo').remove()}
function handleUserPublished(user,mediaType){user.uname=options.uname;const id=user.uid;remoteUsers[id]=user;subscribe(user,mediaType)}
function handleUserUnpublished(user,mediaType){const id=user.uid;if(mediaType==='video'){if(remoteUsers[id]){if(remoteUsers[id]!=='undefined'&&remoteUsers[id]._video_muted_===!0){var username_color=$(`#player-${id}`).closest('.video-tile').attr('name');$(`#player-${id}`).html('<div class="novideo">'+$(`#player-${id}`).closest('.video-tile').attr('namepl').charAt(0)+'</div>');$(`#player-${id}`).find('.novideo').css('background','#'+username_color)}else{$(`#player-wrapper-${id}`).parent('.video-tile').remove()}}else{$(`#player-wrapper-${id}`).parent('.video-tile').remove()}}
if(mediaType==='audio'){if(remoteUsers[id]){if(remoteUsers[id]!=='undefined'&&remoteUsers[id]._audio_muted_===!0){$(`#player-${id}-mute`).removeAttr("name");$(`#player-${id}-mute`).attr('name','microphone-off')}else{$(`#player-${id}-mute`).removeAttr("name");$(`#player-${id}-mute`).attr('name','microphone')}}}
if(remoteUsers[id]==='undefined'){delete remoteUsers[id]}
var player_count=parseInt($('#tiles-count').val());$('#tiles-count').val(player_count);const gapBetweenTiles=10;const wrapper=document.getElementById("remote-playerlist");const input=document.getElementById("tiles-count");const renderNewTiles=(tilesCount)=>{Array.from({length:tilesCount},(_,i)=>i+1).forEach(()=>{})};wrapper.style.gap=`${gapBetweenTiles}px`;renderNewTiles(player_count);const tiles=document.getElementsByClassName("video-tile");const elementsInARowCount=Math.ceil(Math.sqrt(tiles.length));const tilesArray=[...tiles];tilesArray.forEach((element)=>{if(tiles.length>elementsInARowCount){$('.video-tile').addClass('video-tile-2')}else{$('.video-tile').removeClass('video-tile-2')}
if(elementsInARowCount===1){element.style.width=`calc(calc(70% / ${elementsInARowCount}) - ${gapBetweenTiles}px)`}else{element.style.width=`calc(calc(70% / ${elementsInARowCount}) - ${gapBetweenTiles}px)`}})}
var Clock={totalSeconds:0,start:function(){var self=this;this.interval=setInterval(function(){self.totalSeconds+=1;var hours=Math.floor(self.totalSeconds/3600);var minutes=Math.floor(self.totalSeconds/60%60);var seconds=parseInt(self.totalSeconds%60);hours=(hours<10)?"0"+hours:hours;minutes=(minutes<10)?"0"+minutes:minutes;seconds=(seconds<10)?"0"+seconds:seconds;$("#hour").text(hours);$("#min").text(minutes);$("#sec").text(seconds)},1000)},pause:function(){clearInterval(this.interval);delete this.interval},stop:function(){clearInterval(this.interval);delete this.interval;var self=this;self.totalSeconds=0},resume:function(){if(!this.interval)
this.start();}};$(window).on('beforeunload',function(){leave()});$('#apply_effect').click(async function(e){vb_effect=!0;vb_preview_effect=!1;await client.publish(Object.values(localTracks));localTracks.videoTrack.play("local-player");$('#visual_popup').hide();$('#apply_effect').hide()});$('#cancel_popup').click(async function(e){if(vb_preview_effect===!0){try{await processor.disable();processorIsDisable=!0}catch(e){console.error("disable VirtualBackground failure",e)}finally{}
vb_preview_effect=!1}
await client.publish(Object.values(localTracks));localTracks.videoTrack.play("local-player");$('#visual_popup').hide();$('#apply_effect').hide()});$('#open_visuals').click(async(e)=>{e.preventDefault();if($("#mute-video").hasClass("close")==!0){unmuteVideo()}
$('#visual_popup').show();await client.unpublish(Object.values(localTracks));localTracks.videoTrack.play("local-player-1");denoiser=denoiser||((()=>{let denoiser=new VirtualBackgroundExtension();AgoraRTC.registerExtensions([denoiser]);return denoiser})())
processor=processor||(await(async()=>{let processor=denoiser.createProcessor()
processor.eventBus.on("PERFORMANCE_WARNING",()=>{console.warn("Performance warning!!!!!!!!!!!!!!!!!")})
try{await processor.init("./agora/wasms")}catch(error){console.error(error);processor=null}
return processor})());pipeProcessor(localTracks.videoTrack,processor)});$("#disableVirtualBackground").click(async(e)=>{e.preventDefault();try{await processor.disable();processorIsDisable=!0}catch(e){console.error("disable VirtualBackground failure",e)}finally{}
$('.vb_set').css('border','1px solid #ccc');$('#apply_effect').hide()})
$(".vb_set").click(async(e)=>{e.preventDefault();$('.vb_set').css('border','1px solid #ccc');vb_preview_effect=!0;var vb_type=e.currentTarget.id;var vb_name=e.currentTarget.getAttribute('name');if(processorIsDisable){try{await processor.enable();processorIsDisable=!1}catch(e){console.error("enable VirtualBackground failure",e)}finally{}}
$('#vb_loader'+vb_name).show();if(vb_type.includes('https')){tempSelected="image"
optionState.currentImageUrl=e.currentTarget.id}else{tempSelected="blur"
optionState.currentBlurDegree=Number(e.currentTarget.dataset.level)}
currentOption=tempSelected;let option={};switch(currentOption){case "blur":option={type:'blur',blurDegree:Number(optionState.currentBlurDegree)}
break;case "image":option={type:'img',source:await loadImage(optionState.currentImageUrl)}
break}
processor.setOptions(option);e.currentTarget.style.border="1px solid #0E315A";$('#vb_loader'+vb_name).hide();$('#apply_effect').show()})